on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

  workflow_dispatch:
  
jobs:
    my_job:
      name: deploy to staging
      runs-on: ubuntu-18.04
      steps:
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '18.17.0'
        - name: Install dependencies
          run: yarn
        - name: Build project
          run: yarn build
